version: '3.8'

services:
  nextjs-app:
    platform: linux/amd64
    build: .
    container_name: web-portofolio
    image: web-portofolio-image
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
